### ISSUE TITLE
Journal Writings

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/tapaswenipathak.blog#4]
- Get access of https://drive.google.com/drive/folders/1Zigla3id8wwZ_lvQyx5zLc39d1CmtWfW from me. 
- The dirs has writings in text format
- Mathematical graphs
- UML diagrams
- Bar charts
- Text files where GIFs should be created

- Any questions, issues you face please lemme know!

**Comment by tapaswenipathak** [comment]
![polar](https://user-images.githubusercontent.com/4143778/59962694-78c48c00-9506-11e9-8a15-9a31a55303d6.gif)
![gif](https://user-images.githubusercontent.com/4143778/59962625-a0672480-9505-11e9-8eaf-50119181b88c.gif)
![gif1](https://user-images.githubusercontent.com/4143778/59962633-c2f93d80-9505-11e9-9d34-2b394f2f3e6a.gif)
![Equalizer_Chart](https://user-images.githubusercontent.com/4143778/59962640-dc9a8500-9505-11e9-8679-6ff668c48a69.gif)
![tenor (1)](https://user-images.githubusercontent.com/4143778/59962644-f340dc00-9505-11e9-96fe-2cba87acb5c0.gif)

**Comment by tapaswenipathak** [comment]
Tools

https://github.com/tapaswenipathak/Internship#data-visualisation-internship

**Comment by tapaswenipathak** [comment]
Spread using a bot

- Wordpress API parsing the blog post
- Extract GIFs, charts
- Summarise those blog post
- Create a list of topics and terms
- Twitter API words extraction from tweeters
- AI chatbot suggesting people on reading research papers based on what they are tweeting

https://github.com/tapaswenipathak/Bot-list/issues/3

**Comment by tapaswenipathak** [comment]
Made available using a bot

- Wordpress API parsing the blog post
- Extract GIFs, charts
- Summarise those blog post
- Create a list of topics and terms
- Twitter API words extraction from tweeters
- AI chatbot suggesting people on reading research papers based on what they are tweeting

**Comment by code-monk08** [comment]
>     * Text files where GIFs should be created

does this text file contains the position where the GIF should be placed, or does this contains some instructions upon which a GIF should be created?

**Comment by tapaswenipathak** [comment]
https://paper.dropbox.com/doc/blogging-guidelines--Ag5eBBpTknoWVuAVo8UV1N3kAg-iNEReivPXF99MRz3K8b7p
