### ISSUE TITLE
List GIF maker websites/tools

### ISSUE THREAD

**Issue by tapaswenipathak** [alice-sieve/tapaswenipathak.blog#6]
List gif maker tools. Mostly visualisations in form of gifs. You can post as a comment on this ticket.

**Comment by bymayanksingh** [comment]
https://datagifmaker.withgoogle.com

**Comment by bymayanksingh** [comment]
[SmartCharts for Excel](https://appsource.microsoft.com/en-us/product/office/WA104120594?src=office&corrid=144e9fab-4ffc-4446-9b7f-34cb999d15ee&omexanonuid=7634c2c2-2f6b-4acb-b525-cebe4457ddd6&referralurl=https%3a%2f%2fmedium.com%2f%40evansinar%2fuse-animation-to-supercharge-data-visualization-cd905a882ad4)

**Comment by bymayanksingh** [comment]
[p5.js/processing.py](https://processing.org/) : programming based approach.

**Comment by bymayanksingh** [comment]
https://flourish.studio/ +1
